#!/usr/bin/env bun

/**
 * Proof 11: keychain-probe-created item after keychain-probe rebuild.
 *
 * Goal: test whether an item created by keychain-probe can still be read
 * without prompting after keychain-probe is rebuilt and its CDHash changes.
 */

import { unlink } from "node:fs/promises";

const account = "macos-keychain-analysis";
const password = "disposable-proof-secret";
const service = "macos-keychain-analysis.proof-11.probe-created-after-rebuild";
const label = "macos-keychain-analysis proof 11 probe created after rebuild";
const cleanupOnly = Bun.argv.includes("--cleanup");
const packagePath = "packages/keychain-probe";
const probePath = "packages/keychain-probe/.build/arm64-apple-macosx/debug/keychain-probe";
const markerPath = "packages/keychain-probe/Sources/KeychainProbe/Proof11BuildMarker.swift";

type CommandResult = { command: string; exitCode: number; stdout: string; stderr: string };

async function runCommand(args: string[]): Promise<CommandResult> {
  const command = args.map(quoteShell).join(" ");
  console.log(`\n$ ${command}`);
  const proc = Bun.spawn(args, { stdout: "pipe", stderr: "pipe" });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (stdout.trim()) console.log(stdout.trimEnd());
  if (stderr.trim()) console.error(stderr.trimEnd());
  console.log(`exit: ${exitCode}`);
  return { command, stdout, stderr, exitCode };
}

function quoteShell(value: string) {
  if (/^[A-Za-z0-9_./:=@+-]+$/.test(value)) return value;
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

async function runProbe(args: string[]) { return runCommand([probePath, ...args]); }

async function cleanup() {
  await runProbe(["delete", "--service", service, "--account", account]);
  await unlink(markerPath).catch(() => undefined);
}

async function writeBuildMarker(marker: string) {
  await Bun.write(markerPath, `// Generated by proof 11. Safe to delete.\nlet proof11BuildMarker = "${marker}"\n`);
}

async function buildProbe(marker: string) {
  await writeBuildMarker(marker);
  await runCommand(["/usr/bin/swift", "build", "--package-path", packagePath]);
}

async function probeCdhash(): Promise<string> {
  const result = await runCommand(["/usr/bin/codesign", "-d", "-vvv", probePath]);
  const output = `${result.stdout}\n${result.stderr}`;
  const match = output.match(/CDHash=([0-9a-f]+)/i);
  if (!match) throw new Error(`Could not parse CDHash from codesign output:\n${output}`);
  return match[1].toLowerCase();
}

function parseJsonLine<T>(stdout: string): T | undefined {
  const line = stdout.trim().split("\n").find((candidate) => candidate.trim().startsWith("{"));
  if (!line) return undefined;
  return JSON.parse(line) as T;
}

async function readWithProbe(label: string) {
  console.log(`\n### ${label}`);
  const read = await runProbe(["read", "--service", service, "--account", account]);
  const parsed = parseJsonLine<{ ok: boolean; result?: { value?: string } }>(read.stdout);
  console.log(`read matched expected disposable secret: ${parsed?.result?.value === password ? "yes" : "no"}`);
}

async function main() {
  console.log("# Proof 11: keychain-probe-created item after keychain-probe rebuild");

  if (cleanupOnly) {
    console.log("\n## Cleanup only");
    await cleanup();
    return;
  }

  console.log("\n## What to record manually");
  console.log("Record whether create, pre-rebuild reads, ACL lists, or post-rebuild reads prompt.");
  console.log("Expected question: does creator ownership survive a changed CDHash?");

  console.log("\n## Build initial keychain-probe");
  await buildProbe(`initial-${Date.now()}`);
  const firstCdhash = await probeCdhash();
  console.log(`initial keychain-probe CDHash: ${firstCdhash}`);

  console.log("\n### Setup: remove stale item");
  await runProbe(["delete", "--service", service, "--account", account]);

  console.log("\n### Create item via keychain-probe");
  await runProbe(["add", "--service", service, "--account", account, "--value", password, "--label", label]);

  await readWithProbe("First password read via original keychain-probe");
  await readWithProbe("Second password read via original keychain-probe");

  console.log("\n### ACL list before rebuild");
  await runProbe(["acl-list", "--service", service, "--account", account]);

  console.log("\n## Rebuild keychain-probe with changed source marker");
  await buildProbe(`rebuilt-${Date.now()}`);
  const secondCdhash = await probeCdhash();
  console.log(`rebuilt keychain-probe CDHash: ${secondCdhash}`);
  console.log(`CDHash changed: ${secondCdhash !== firstCdhash ? "yes" : "no"}`);
  if (secondCdhash === firstCdhash) {
    console.log("WARNING: CDHash did not change; this run cannot test rebuild invalidation.");
  }

  await readWithProbe("First password read after keychain-probe rebuild");
  await readWithProbe("Second password read after keychain-probe rebuild");

  console.log("\n### ACL list after post-rebuild reads");
  await runProbe(["acl-list", "--service", service, "--account", account]);

  console.log("\n## Cleanup command");
  console.log("bun run proof:11:cleanup");
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
