#!/usr/bin/env bun

/**
 * Proof 10: Always Allow after keychain-probe rebuild.
 *
 * Goal: test whether a Keychain item that was allowed via the GUI "Always Allow"
 * prompt stays allowed after rebuilding keychain-probe with a changed CDHash.
 *
 * Manual step: when the first keychain-probe read prompts, choose Always Allow.
 */

import { unlink } from "node:fs/promises";

const account = "macos-keychain-analysis";
const password = "disposable-proof-secret";
const service = "macos-keychain-analysis.proof-10.always-allow-after-probe-rebuild";
const label = "macos-keychain-analysis proof 10 always allow after probe rebuild";
const cleanupOnly = Bun.argv.includes("--cleanup");
const packagePath = "packages/keychain-probe";
const probePath = "packages/keychain-probe/.build/arm64-apple-macosx/debug/keychain-probe";
const securityPath = "/usr/bin/security";
const markerPath = "packages/keychain-probe/Sources/KeychainProbe/Proof10BuildMarker.swift";

type CommandResult = { command: string; exitCode: number; stdout: string; stderr: string };

async function runCommand(args: string[]): Promise<CommandResult> {
  const command = args.map(quoteShell).join(" ");
  console.log(`\n$ ${command}`);
  const proc = Bun.spawn(args, { stdout: "pipe", stderr: "pipe" });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (stdout.trim()) console.log(stdout.trimEnd());
  if (stderr.trim()) console.error(stderr.trimEnd());
  console.log(`exit: ${exitCode}`);
  return { command, stdout, stderr, exitCode };
}

function quoteShell(value: string) {
  if (/^[A-Za-z0-9_./:=@+-]+$/.test(value)) return value;
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

async function runProbe(args: string[]) { return runCommand([probePath, ...args]); }
async function runSecurity(args: string[]) { return runCommand([securityPath, ...args]); }

async function cleanup() {
  await runSecurity(["delete-generic-password", "-a", account, "-s", service]);
  await unlink(markerPath).catch(() => undefined);
}

async function writeBuildMarker(marker: string) {
  await Bun.write(markerPath, `// Generated by proof 10. Safe to delete.\nlet proof10BuildMarker = "${marker}"\n`);
}

async function buildProbe(marker: string) {
  await writeBuildMarker(marker);
  await runCommand(["/usr/bin/swift", "build", "--package-path", packagePath]);
}

async function probeCdhash(): Promise<string> {
  const result = await runCommand(["/usr/bin/codesign", "-d", "-vvv", probePath]);
  const output = `${result.stdout}\n${result.stderr}`;
  const match = output.match(/CDHash=([0-9a-f]+)/i);
  if (!match) throw new Error(`Could not parse CDHash from codesign output:\n${output}`);
  return match[1].toLowerCase();
}

function parseJsonLine<T>(stdout: string): T | undefined {
  const line = stdout.trim().split("\n").find((candidate) => candidate.trim().startsWith("{"));
  if (!line) return undefined;
  return JSON.parse(line) as T;
}

async function readWithProbe(label: string) {
  console.log(`\n### ${label}`);
  const read = await runProbe(["read", "--service", service, "--account", account]);
  const parsed = parseJsonLine<{ ok: boolean; result?: { value?: string } }>(read.stdout);
  console.log(`read matched expected disposable secret: ${parsed?.result?.value === password ? "yes" : "no"}`);
}

async function main() {
  console.log("# Proof 10: Always Allow after keychain-probe rebuild");

  if (cleanupOnly) {
    console.log("\n## Cleanup only");
    await cleanup();
    return;
  }

  console.log("\n## What to record manually");
  console.log("On the first keychain-probe read, choose Always Allow.");
  console.log("Record whether the second read before rebuild is silent, and whether the read after rebuild prompts again.");

  console.log("\n## Build initial keychain-probe");
  await buildProbe(`initial-${Date.now()}`);
  const firstCdhash = await probeCdhash();
  console.log(`initial keychain-probe CDHash: ${firstCdhash}`);

  console.log("\n### Setup: remove stale item");
  await runSecurity(["delete-generic-password", "-a", account, "-s", service]);

  console.log("\n### Create item via /usr/bin/security");
  await runSecurity(["add-generic-password", "-a", account, "-s", service, "-w", password, "-l", label]);

  await readWithProbe("First password read via keychain-probe — choose Always Allow in the GUI prompt");
  await readWithProbe("Second password read via keychain-probe — verifies Always Allow before rebuild");

  console.log("\n### ACL list after Always Allow before rebuild");
  await runProbe(["acl-list", "--service", service, "--account", account]);

  console.log("\n## Rebuild keychain-probe with changed source marker");
  await buildProbe(`rebuilt-${Date.now()}`);
  const secondCdhash = await probeCdhash();
  console.log(`rebuilt keychain-probe CDHash: ${secondCdhash}`);
  console.log(`CDHash changed: ${secondCdhash !== firstCdhash ? "yes" : "no"}`);
  if (secondCdhash === firstCdhash) {
    console.log("WARNING: CDHash did not change; this run cannot test rebuild invalidation.");
  }

  await readWithProbe("Password read after keychain-probe rebuild");

  console.log("\n### ACL list after post-rebuild read");
  await runProbe(["acl-list", "--service", service, "--account", account]);

  console.log("\n## Expected result");
  console.log("If Always Allow is tied to cdhash, the post-rebuild read prompts again because the CDHash changed.");

  console.log("\n## Cleanup command");
  console.log("bun run proof:10:cleanup");
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
