#!/usr/bin/env bun

/**
 * Proof 13: security-created item, Always Allow, signed keychain-probe after rebuild.
 *
 * Goal: test whether a Keychain item created by /usr/bin/security and then
 * Always Allowed for a stably signed keychain-probe remains readable after
 * keychain-probe is rebuilt and re-signed with the same identity.
 *
 * Manual step: when the first keychain-probe read prompts, choose Always Allow.
 */

import { unlink } from "node:fs/promises";

const account = "macos-keychain-analysis";
const password = "disposable-proof-secret";
const service = "macos-keychain-analysis.proof-13.security-created-signed-always-allow-rebuild";
const label = "macos-keychain-analysis proof 13 security created signed always allow rebuild";
const cleanupOnly = Bun.argv.includes("--cleanup");
const packagePath = "packages/keychain-probe";
const probePath = "packages/keychain-probe/.build/arm64-apple-macosx/debug/keychain-probe";
const markerPath = "packages/keychain-probe/Sources/KeychainProbe/Proof13BuildMarker.swift";
const securityPath = "/usr/bin/security";
const signingIdentity = process.env.PROOF13_CODESIGN_IDENTITY
  ?? process.env.PROOF12_CODESIGN_IDENTITY
  ?? "584EFC30BFC2F2BAC6BC900457C8BB19671D0D18";
const signingIdentifier = "dev.bjesuiter.macos-keychain-analysis.keychain-probe";

type CommandResult = { command: string; exitCode: number; stdout: string; stderr: string };

async function runCommand(args: string[], options: { allowFailure?: boolean } = {}): Promise<CommandResult> {
  const command = args.map(quoteShell).join(" ");
  console.log(`\n$ ${command}`);
  const proc = Bun.spawn(args, { stdout: "pipe", stderr: "pipe" });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (stdout.trim()) console.log(stdout.trimEnd());
  if (stderr.trim()) console.error(stderr.trimEnd());
  console.log(`exit: ${exitCode}`);
  if (!options.allowFailure && exitCode !== 0) {
    throw new Error(`Command failed (${exitCode}): ${command}`);
  }
  return { command, stdout, stderr, exitCode };
}

function quoteShell(value: string) {
  if (/^[A-Za-z0-9_./:=@+-]+$/.test(value)) return value;
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

async function runProbe(args: string[], options: { allowFailure?: boolean } = {}) {
  return runCommand([probePath, ...args], options);
}
async function runSecurity(args: string[], options: { allowFailure?: boolean } = {}) {
  return runCommand([securityPath, ...args], options);
}

async function cleanup() {
  await runSecurity(["delete-generic-password", "-a", account, "-s", service], { allowFailure: true });
  await unlink(markerPath).catch(() => undefined);
}

async function writeBuildMarker(marker: string) {
  await Bun.write(markerPath, `// Generated by proof 13. Safe to delete.\nlet proof13BuildMarker = "${marker}"\n`);
}

async function signProbe() {
  await runCommand([
    "/usr/bin/codesign",
    "--force",
    "--sign", signingIdentity,
    "--identifier", signingIdentifier,
    probePath,
  ]);
}

async function buildAndSignProbe(marker: string) {
  await writeBuildMarker(marker);
  await runCommand(["/usr/bin/swift", "build", "--package-path", packagePath]);
  await signProbe();
}

async function codeIdentity(label: string): Promise<{ cdhash: string; requirement: string }> {
  console.log(`\n### Code identity: ${label}`);
  const result = await runCommand(["/usr/bin/codesign", "-d", "-vvv", "-r-", probePath]);
  const output = `${result.stdout}\n${result.stderr}`;
  const cdhash = output.match(/CDHash=([0-9a-f]+)/i)?.[1]?.toLowerCase();
  const requirement = output.match(/designated => (.+)/)?.[1]?.trim() ?? "";
  if (!cdhash) throw new Error(`Could not parse CDHash from codesign output:\n${output}`);
  console.log(`parsed CDHash: ${cdhash}`);
  console.log(`parsed designated requirement: ${requirement || "<none>"}`);
  return { cdhash, requirement };
}

function parseJsonLine<T>(stdout: string): T | undefined {
  const line = stdout.trim().split("\n").find((candidate) => candidate.trim().startsWith("{"));
  if (!line) return undefined;
  return JSON.parse(line) as T;
}

async function readWithProbe(label: string) {
  console.log(`\n### ${label}`);
  const read = await runProbe(["read", "--service", service, "--account", account]);
  const parsed = parseJsonLine<{ ok: boolean; result?: { value?: string } }>(read.stdout);
  console.log(`read matched expected disposable secret: ${parsed?.result?.value === password ? "yes" : "no"}`);
}

async function main() {
  console.log("# Proof 13: security-created Always Allow for signed keychain-probe after rebuild");
  console.log(`codesign identity: ${signingIdentity}`);
  console.log(`codesign identifier: ${signingIdentifier}`);

  if (cleanupOnly) {
    console.log("\n## Cleanup only");
    await cleanup();
    return;
  }

  console.log("\n## What to record manually");
  console.log("On the first keychain-probe read, choose Always Allow.");
  console.log("Record whether the post-rebuild read prompts again.");
  console.log("Expected question: does Always Allow use teamid/designated requirement for a signed probe, or cdhash?");

  console.log("\n## Build and sign initial keychain-probe");
  await buildAndSignProbe(`initial-${Date.now()}`);
  const firstIdentity = await codeIdentity("initial signed probe");

  console.log("\n### Setup: remove stale item");
  await runSecurity(["delete-generic-password", "-a", account, "-s", service], { allowFailure: true });

  console.log("\n### Create item via /usr/bin/security");
  await runSecurity(["add-generic-password", "-a", account, "-s", service, "-w", password, "-l", label]);

  await readWithProbe("First password read via signed keychain-probe — choose Always Allow");
  await readWithProbe("Second password read before rebuild — verifies Always Allow");

  console.log("\n### ACL list after Always Allow before rebuild");
  await runProbe(["acl-list", "--service", service, "--account", account]);

  console.log("\n## Rebuild and re-sign keychain-probe");
  await buildAndSignProbe(`rebuilt-${Date.now()}`);
  const secondIdentity = await codeIdentity("rebuilt signed probe");
  console.log(`CDHash changed: ${secondIdentity.cdhash !== firstIdentity.cdhash ? "yes" : "no"}`);
  console.log(`designated requirement changed: ${secondIdentity.requirement !== firstIdentity.requirement ? "yes" : "no"}`);

  await readWithProbe("First password read after rebuild/re-sign");
  await readWithProbe("Second password read after rebuild/re-sign");

  console.log("\n### ACL list after post-rebuild reads");
  await runProbe(["acl-list", "--service", service, "--account", account]);

  console.log("\n## Cleanup command");
  console.log("bun run proof:13:cleanup");
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
